name: "aws"
on:
  pull_request:
  push:
jobs:
  upload:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            build-users-group = nixbld
            max-jobs = 16
            cores = 16
            sandbox = false
            auto-optimise-store = true
      - run: |
          nix-build -A nixpkgs.tarball $GITHUB_WORKSPACE/nixos/release-aira.nix -I nixpkgs=$GITHUB_WORKSPACE
          mkdir $GITHUB_RUN_ID
          cp $GITHUB_WORKSPACE/result/tarballs/*.tar.xz $GITHUB_RUN_ID/nixexprs.tar.xz
      - run: |
          nix-build -A ova_image_unstable $GITHUB_WORKSPACE/nixos/release-aira-images.nix -I nixpkgs=$GITHUB_WORKSPACE
          cp $GITHUB_WORKSPACE/result/*.ova $GITHUB_RUN_ID/
      - run: |
          cd $GITHUB_RUN_ID
          tree -P "*.tar.gz|*.tar.xz|*.ova" -h -D --dirsfirst -r -H . > index.html
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - run: |
          echo "Upload files"
          ws s3 cp --recursive  $GITHUB_RUN_ID/ s3://releases.aira.life/channels/aira/unstable/$GITHUB_RUN_ID
          echo "Generate nginx config"
          mkdir conf
          echo 'location ~ ^/channels/aira-unstable(.*)$ { index index.html;try_files $uri $uri/ @unstable;}' > conf/unstable.conf
          echo 'location @unstable { return 302  https://releases.aira.life/channels/aira/unstable/'$GITHUB_RUN_ID'$1;}' >> conf/unstable.conf
          aws s3 cp conf/unstable.conf s3://releases.aira.life/conf/unstable.conf
        shell: bash
